platform :ios, '7.0'

pod 'ReactiveCocoa', '~> 2.5'
pod 'ReactiveViewModel', tag: '0.1.2', git: 'https://github.com/ashfurrow/ReactiveViewModel.git'
pod '500px-iOS-api'
pod 'SVProgressHUD', '1.0'
pod 'AFImageDownloader', '1.0.0'
use_frameworks!

